# Generated by Django 5.1.6 on 2025-08-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
