# Generated by Django 5.1.6 on 2025-08-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='bank_logos/'),
        ),
    ]
